# Name of the Namespace to use
namespace: mongodb

## Operator
operator:
  # Name that will be assigned to most of internal Kubernetes objects like Deployment, ServiceAccount, Role etc.
  name: mongodb-kubernetes-operator

  # Name of the operator image
  operator_image_name: mongodb-kubernetes-operator

  # Name of the deployment of the operator pod
  deployment_name: mongodb-kubernetes-operator

  # Version of mongodb-kubernetes-operator
  version: 0.7.0

  # The Custom Resources that will be watched by the Operator. Needs to be changed if only some of the CRDs are installed
  # TODO: Verify it's necessary
  watchedResources:
    - mongodb

  metadata:
    email: support@mongodb.com
database:
  name: mongodb-database

agent:
  name: mongodb-agent
  version: 11.0.5.6963-1
version_upgrade_hook:
  name: mongodb-kubernetes-operator-version-upgrade-post-start-hook
  version: 1.0.2
readiness_probe:
  name: mongodb-kubernetes-readinessprobe
  version: 1.0.4
mongodb:
  name: mongodb
  repo: docker.io


registry:
  agent: quay.io/mongodb
  version_upgrade_hook: quay.io/mongodb
  readiness_probe: quay.io/mongodb
  operator: quay.io/mongodb
  pullPolicy: Always


config:
  repo_url: localhost:5000
  operator_image: mongodb-kubernetes-operator
  e2e_image: community-e2e
  version_upgrade_hook_image: community-operator-version-upgrade-post-start-hook
  agent_image_ubuntu: mongodb-agent-dev
  agent_image_ubi: mongodb-agent-ubi-dev
  readiness_probe_image: mongodb-kubernetes-readiness
  s3_bucket: ""

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80



nodeSelector: {}

tolerations: []

affinity: {}
